name: Node.js CI (24/7)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:  # Ajout du déclencheur programmé
    - cron: '0 0-23/5 * * *'  # Toutes les 5 heures

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run application continuously
      run: |
        npm start &
        # Maintient le job actif jusqu'à la limite de temps
        while true; do
          sleep 3600
        done
